import { Project, Member, Task, AvailabilityBlock, Meeting, AsyncUpdate } from "@/types";

export const SEEDED_MEMBERS: Member[] = [
  {
    id: "mem-ammar",
    name: "Ammar Almeher",
    role: "Full-Stack & Integration Lead",
    skills: ["TypeScript", "Next.js", "Tailwind CSS", "System Design"],
    wantsToLearn: ["Real-time Sync", "Edge Runtimes"],
    initials: "AA",
  },
  {
    id: "mem-divij",
    name: "Divij Anand",
    role: "Backend & Systems Specialist",
    skills: ["Node.js", "API Architecture", "Database Schema", "Prompt Engineering"],
    wantsToLearn: ["LLM Agents", "Vector Databases"],
    initials: "DA",
  },
  {
    id: "mem-oscar",
    name: "Oscar Garcia",
    role: "Core Logic & Algorithms Lead",
    skills: ["TypeScript", "Data Structures", "Algorithm Optimization", "Testing"],
    wantsToLearn: ["Constraint Solvers", "Distributed Systems"],
    initials: "OG",
  },
  {
    id: "mem-shreya",
    name: "Shreya Rameshwar",
    role: "Product & Async Collaboration Lead",
    skills: ["Frontend UI", "UX Flow", "State Management", "Documentation"],
    wantsToLearn: ["AI Summarization Pipelines", "Accessibility"],
    initials: "SR",
  },
];

export const SEEDED_TASKS: Task[] = [
  {
    id: "task-1",
    projectId: "proj-csc-app",
    title: "Project Architecture & Shell Setup",
    description: "Establish Next.js App Router scaffolding, layout shell, and shared TypeScript interfaces.",
    ownerId: "mem-ammar",
    suggestedOwnerId: "mem-ammar",
    status: "done",
    dependencies: [],
    estimatedMinutes: 120,
    dueDate: "2026-10-04",
    assignmentReason: "Strong full-stack and project scaffolding background.",
  },
  {
    id: "task-2",
    projectId: "proj-csc-app",
    title: "Collaborative Canvas & State Sync",
    description: "Design shared state protocol for real-time collaboration canvas.",
    ownerId: "mem-ammar",
    suggestedOwnerId: "mem-ammar",
    status: "in-progress",
    dependencies: ["task-1"],
    estimatedMinutes: 180,
    dueDate: "2026-10-08",
    assignmentReason: "Aligns with goal to master real-time synchronization.",
  },
  {
    id: "task-3",
    projectId: "proj-csc-app",
    title: "REST / Server Action API Routes",
    description: "Implement API endpoints for team persistence, room management, and session handling.",
    ownerId: "mem-divij",
    suggestedOwnerId: "mem-divij",
    status: "in-progress",
    dependencies: ["task-1"],
    estimatedMinutes: 150,
    dueDate: "2026-10-07",
    assignmentReason: "Expertise in backend architecture and clean API boundaries.",
  },
  {
    id: "task-4",
    projectId: "proj-csc-app",
    title: "Availability Overlap Algorithm",
    description: "Create deterministic time intersection algorithm to locate optimal team meeting windows.",
    ownerId: "mem-oscar",
    suggestedOwnerId: "mem-oscar",
    status: "todo",
    dependencies: ["task-1"],
    estimatedMinutes: 90,
    dueDate: "2026-10-09",
    assignmentReason: "Fits algorithm optimization background and constraint solving interest.",
  },
  {
    id: "task-5",
    projectId: "proj-csc-app",
    title: "Meeting Brief & Catch-Up Workflow",
    description: "Build user interface for asynchronous standup updates, meeting briefs, and catch-up summaries.",
    ownerId: "mem-shreya",
    suggestedOwnerId: "mem-shreya",
    status: "todo",
    dependencies: ["task-1"],
    estimatedMinutes: 120,
    dueDate: "2026-10-10",
    assignmentReason: "Aligns with product workflow and async communication ownership.",
  },
  {
    id: "task-6",
    projectId: "proj-csc-app",
    title: "Integration Testing & Demo Presentation Deck",
    description: "End-to-end verification of collaborative web app and preparation of slide deck for course demo.",
    suggestedOwnerId: "mem-shreya",
    status: "blocked",
    dependencies: ["task-2", "task-3", "task-4", "task-5"],
    estimatedMinutes: 140,
    dueDate: "2026-10-14",
    assignmentReason: "Depends on completion of core features prior to final dry run.",
  },
];

export const SEEDED_AVAILABILITY: AvailabilityBlock[] = [
  { id: "av-1", memberId: "mem-ammar", dayOfWeek: "Thu", startTime: "14:00", endTime: "18:00", isAvailable: true },
  { id: "av-2", memberId: "mem-divij", dayOfWeek: "Thu", startTime: "15:00", endTime: "19:00", isAvailable: true },
  { id: "av-3", memberId: "mem-oscar", dayOfWeek: "Thu", startTime: "13:00", endTime: "17:00", isAvailable: true },
  { id: "av-4", memberId: "mem-shreya", dayOfWeek: "Thu", startTime: "15:00", endTime: "17:00", isAvailable: true },
  { id: "av-5", memberId: "mem-ammar", dayOfWeek: "Fri", startTime: "10:00", endTime: "14:00", isAvailable: true },
  { id: "av-6", memberId: "mem-divij", dayOfWeek: "Fri", startTime: "11:00", endTime: "15:00", isAvailable: true },
  { id: "av-7", memberId: "mem-oscar", dayOfWeek: "Fri", startTime: "10:00", endTime: "13:00", isAvailable: true },
  { id: "av-8", memberId: "mem-shreya", dayOfWeek: "Fri", startTime: "13:00", endTime: "16:00", isAvailable: true },
];

export const SEEDED_MEETINGS: Meeting[] = [
  {
    id: "meet-1",
    projectId: "proj-csc-app",
    title: "Sprint 1 Sync & Architecture Hand-off",
    scheduledTime: "Thursday, Oct 9 • 3:30 PM – 4:15 PM",
    durationMinutes: 45,
    attendeeIds: ["mem-ammar", "mem-divij", "mem-oscar"],
    agendaItems: [
      "Review component boundaries and shared types",
      "API route contracts for session state",
      "Assign next sprint deliverable owners",
    ],
    summary: "Finalized core app router shell and task schema. Discussed handoff for API routes and overlap calculation.",
    catchUpNotes: "Shreya could not attend due to concurrent lab section. Catch-up digest generated with action items.",
  },
];

export const SEEDED_ASYNC_UPDATES: AsyncUpdate[] = [
  {
    id: "upd-1",
    projectId: "proj-csc-app",
    memberId: "mem-shreya",
    meetingId: "meet-1",
    type: "cant_attend",
    content: "I have a scheduled physics lab conflict during Thursday 3:30 PM. I will review the meeting brief and post my progress update asynchronously.",
    createdAt: "2026-10-09T14:15:00Z",
  },
];

export const INITIAL_DEMO_PROJECT: Project = {
  id: "proj-csc-app",
  name: "CSC Group Web Application Project",
  course: "CSC 648: Software Engineering",
  description: "Collaborative multiplayer web application featuring real-time state sync, secure backend persistence, robust API routes, and automated end-to-end testing.",
  deadline: "October 16, 2026",
  members: SEEDED_MEMBERS,
  tasks: SEEDED_TASKS,
  availability: SEEDED_AVAILABILITY,
  meetings: SEEDED_MEETINGS,
  asyncUpdates: SEEDED_ASYNC_UPDATES,
};
